title: Bout Labs
email: jcurry@boutlabs.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.boutlabs.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: boutlabs
github_username:  BoutLabs
capsule_webform_key: e9dfc9a9-f758-4f73-87ea-0bc3f71107c1
google_tracking_id: UA-143690680-1
timezone: America/New_York

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
permalink: pretty
# paginate: 10
# paginate_path: "/blog/page:num/"

collections:
  services:
    available: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
