name: Checks

on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 0

      - name: HTMLProofer
        run: bundle exec rake test
